import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import { Toaster } from "@/components/ui/sonner";
import ModalProviders from "@/components/providers/modal-providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" h-full w-full flex ">
          <Toaster />
          <ModalProviders />
          <Sidebar />
          <main className=" h-full w-full overflow-auto">{children}</main>
        </div>
      </body>
    </html>
  );
}
